CREATE DATABASE IF NOT EXISTS Quotes;

USE Quotes;

CREATE TABLE IF NOT EXISTS Quote 
(
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  base VARCHAR(256) NOT NULL,
  quote VARCHAR(256) NOT NULL,
  bid DECIMAL(20, 10) NOT NULL,
  ask DECIMAL(20, 10) NOT NULL,
  createdAt BIGINT NOT NULL,
  hash_id INT
);

CREATE TABLE IF NOT EXISTS Hash
(
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  val VARCHAR(64) NOT NULL
);